services:
  app:
    image: node:latest
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/frontend
    command: sh -c "npm install && npm run dev"
    container_name: frontend
    working_dir: /frontend
    